### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by dnlsrl** [dnlsrl/Specschecker#2]
- [ ] Make it a installable package
- [ ] Save info to a database in %APPDATA% and make the program point to it instead of querying all the specs over again
- [ ] Create a GTK+ or QT5 simple GUI for it
- [ ] Make it Linux compatible
